services:
  spring-boot-app:
    build: .
    container_name: springboot
    ports:
      - "3333:8081"
    volumes:
      - /home/ubuntu/app.jar:/app.jar
    entrypoint: ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]
