services:
  spring-boot-app:
    image: ubuntu-spring-boot-app
    container_name: springboot
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Seoul
    ports:
      - "3333:8081"
    volumes:
      - /home/ubuntu/app.jar:/app.jar
      - /home/ubuntu/application-secret.yml:/application-secret.yml
    entrypoint: ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]
