spring:
  profiles:
    active: secret
  jackson:
    serialization:
      fail-on-empty-beans: false
    time-zone: Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

server:
  port: 8081
  servlet:
    context-path: /api
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB