name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 소스 코드 체크아웃
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Spring Boot Application
      run: |
        ./gradlew bootJar  # .jar 파일 생성

    - name: SSH 키 파일 생성
      run: |
        mkdir -p ~/.ssh  # .ssh 디렉토리 생성
        echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa  # SSH 키 파일 생성
        chmod 600 ~/.ssh/id_rsa  # 적절한 권한 설정
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}

    - name: EC2에 파일 배포
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        # 빌드된 .jar 파일과 docker-compose.yml을 EC2로 전송
        scp -i ~/.ssh/id_rsa -o "StrictHostKeyChecking=no" build/libs/misaeng-0.0.1-SNAPSHOT.jar $EC2_USER@$EC2_HOST:/home/ubuntu/app.jar
        scp -i ~/.ssh/id_rsa -o "StrictHostKeyChecking=no" docker-compose.yml $EC2_USER@$EC2_HOST:/home/ubuntu/

    - name: EC2에서 Docker Compose 실행
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        # EC2에서 Docker Compose로 컨테이너 빌드 및 시작
        ssh -i ~/.ssh/id_rsa -o "StrictHostKeyChecking=no" $EC2_USER@$EC2_HOST "
          cd /home/ubuntu &&
          sudo docker-compose down &&
          sudo docker-compose up -d --build
        "
